from __future__ import annotations

from typing import Any

from app.i18n import normalize_locale


_TRACE_LABEL_CATALOG = {
    "zh-CN": {
        "run.started": "开始处理请求",
        "run.finished": "完成",
        "run.failed": "执行失败",
        "runtime_contract.selected": "Full Auto runtime 已启用",
        "runtime_contract.detail": "工具策略：需要时使用",
        "llm.started": "模型开始分析",
        "llm.finished": "模型分析完成",
        "llm.failed": "LLM 请求失败",
        "action.detected": "检测到模型行动：{tool}",
        "action.validating": "验证行动边界：{tool}",
        "action.allowed": "行动通过验证：{tool}",
        "action.blocked": "行动被边界拦截：{tool}",
        "tool.call_detected": "检测到工具调用：{tool}",
        "tool.guard": "工具检查：{tool}",
        "tool.started": "调用工具：{tool}",
        "tool.finished": "工具完成：{tool}",
        "tool.failed": "工具失败：{tool}",
        "observation.returned": "已将观察结果返回模型：{tool}",
        "loop.safeguard": "循环保护触发",
        "approval.required": "需要确认",
        "approval.approved": "确认已放行",
        "approval.resolved": "确认已处理",
        "repair.started": "开始修复执行偏差",
        "repair.finished": "执行偏差修复完成",
        "activity.started": "开始分析请求",
        "activity.delta": "处理中",
        "activity.done": "已确定回答路径",
        "answer.started": "开始生成回答",
        "answer.delta": "正在流式生成回答",
        "answer.done": "生成回答完成",
        "answer.finished": "生成回答完成",
        "blocked": "已阻塞",
        "cancelled": "已取消",
    },
    "ja-JP": {
        "run.started": "リクエストの処理を開始",
        "run.finished": "完了",
        "run.failed": "実行失敗",
        "runtime_contract.selected": "Full Auto runtime を有効化",
        "runtime_contract.detail": "ツール方針：必要なときのみ使用",
        "llm.started": "モデルが解析を開始",
        "llm.finished": "モデル解析が完了",
        "llm.failed": "LLM リクエストに失敗しました",
        "action.detected": "モデル行動を検出: {tool}",
        "action.validating": "行動境界を検証: {tool}",
        "action.allowed": "行動が検証を通過: {tool}",
        "action.blocked": "行動が境界でブロック: {tool}",
        "tool.call_detected": "ツール呼び出しを検出: {tool}",
        "tool.guard": "ツール検査: {tool}",
        "tool.started": "ツール呼び出し: {tool}",
        "tool.finished": "ツール完了: {tool}",
        "tool.failed": "ツール失敗: {tool}",
        "observation.returned": "観察結果をモデルへ返却: {tool}",
        "loop.safeguard": "ループ保護が発動",
        "approval.required": "確認が必要",
        "approval.approved": "確認済み実行を許可",
        "approval.resolved": "確認が処理されました",
        "repair.started": "実行修復を開始",
        "repair.finished": "実行修復が完了",
        "activity.started": "リクエスト分析を開始",
        "activity.delta": "処理中",
        "activity.done": "回答方針を確定",
        "answer.started": "回答の生成を開始",
        "answer.delta": "回答をストリーミング中",
        "answer.done": "回答の生成が完了",
        "answer.finished": "回答の生成が完了",
        "blocked": "停止",
        "cancelled": "キャンセル済み",
    },
    "en": {
        "run.started": "Started processing request",
        "run.finished": "Completed",
        "run.failed": "Run failed",
        "runtime_contract.selected": "Full Auto runtime enabled",
        "runtime_contract.detail": "Tool policy: use when needed",
        "llm.started": "Model analysis started",
        "llm.finished": "Model analysis finished",
        "llm.failed": "LLM request failed",
        "action.detected": "Model action detected: {tool}",
        "action.validating": "Validating action boundary: {tool}",
        "action.allowed": "Action validation passed: {tool}",
        "action.blocked": "Action blocked by boundary: {tool}",
        "tool.call_detected": "Tool call detected: {tool}",
        "tool.guard": "Tool guard: {tool}",
        "tool.started": "Calling tool: {tool}",
        "tool.finished": "Tool finished: {tool}",
        "tool.failed": "Tool failed: {tool}",
        "observation.returned": "Observation returned to model: {tool}",
        "loop.safeguard": "Loop safeguard triggered",
        "approval.required": "Needs confirmation",
        "approval.approved": "Approved execution",
        "approval.resolved": "Confirmation resolved",
        "repair.started": "Repairing execution flow",
        "repair.finished": "Execution flow repaired",
        "activity.started": "Analyzing request",
        "activity.delta": "Working",
        "activity.done": "Answer path selected",
        "answer.started": "Generating answer",
        "answer.delta": "Streaming answer",
        "answer.done": "Answer generation finished",
        "answer.finished": "Answer generation finished",
        "blocked": "Blocked",
        "cancelled": "Cancelled",
    },
}


def trace_label(locale: str, key: str, **replacements: Any) -> str:
    table = _TRACE_LABEL_CATALOG.get(normalize_locale(locale), _TRACE_LABEL_CATALOG["en"])
    template = table.get(key, key)
    try:
        return template.format(**replacements)
    except Exception:
        return template
