from __future__ import annotations

from typing import Any


_FALLBACK_REQUIRES = {
    "workspace_read": False,
    "workspace_write": False,
    "shell": False,
    "network": False,
    "browser": False,
    "optional_dependency": [],
}

FALLBACK_TOOL_METADATA: dict[str, Any] = {
    "group": "unknown",
    "source": "unknown",
    "read_only": False,
    "requires_evidence": False,
    "requires": dict(_FALLBACK_REQUIRES),
    "risk": "unknown",
    "summary": "",
}


TOOL_GROUP_ORDER: dict[str, int] = {
    "control": 0,
    "shell": 1,
    "edit": 2,
    "file": 3,
    "document": 4,
    "web": 5,
    "browser": 6,
    "media": 7,
    "session": 8,
    "archive": 9,
    "unknown": 99,
}


TOOL_METADATA: dict[str, dict[str, Any]] = {
    "update_plan": {
        "group": "control",
        "source": "native",
        "read_only": True,
        "requires_evidence": False,
        "requires": {**_FALLBACK_REQUIRES},
        "risk": "low",
        "summary": "synchronize a lightweight plan",
    },
    "request_user_input": {
        "group": "control",
        "source": "native",
        "read_only": True,
        "requires_evidence": False,
        "requires": {**_FALLBACK_REQUIRES},
        "risk": "low",
        "summary": "request structured follow-up input",
    },
    "load_skill": {
        "group": "control",
        "source": "native",
        "read_only": True,
        "requires_evidence": False,
        "requires": {**_FALLBACK_REQUIRES},
        "risk": "low",
        "summary": "load selected skill instructions",
    },
    "run_skill_script": {
        "group": "shell",
        "source": "native",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": True,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "high",
        "summary": "run a Python resource from an enabled loaded Skill",
    },
    "save_skill": {
        "group": "control",
        "source": "native",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": False,
            "workspace_write": True,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "create or update repository-shared Team Skills",
    },
    "exec_command": {
        "group": "shell",
        "source": "adapter",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": True,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "high",
        "summary": "run workspace shell commands",
    },
    "write_stdin": {
        "group": "shell",
        "source": "adapter",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": True,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "high",
        "summary": "write to a running shell session",
    },
    "apply_patch": {
        "group": "edit",
        "source": "native",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": True,
            "workspace_write": True,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "apply a workspace patch",
    },
    "read_file": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "read one local file",
    },
    "list_dir": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "list one local directory",
    },
    "glob_file_search": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "find files by glob pattern",
    },
    "search_contents_in_file": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "search one local file",
    },
    "search_contents_in_file_multi": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "search one local file with multiple queries",
    },
    "read_section": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "read one matched section",
    },
    "search_codebase": {
        "group": "file",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "search codebase",
    },
    "table_extract": {
        "group": "document",
        "source": "optional",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": ["pypdf", "openpyxl"],
        },
        "risk": "medium",
        "summary": "extract document tables",
    },
    "fact_check_file": {
        "group": "document",
        "source": "optional",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "fact check one file",
    },
    "web_search": {
        "group": "web",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "search the web",
    },
    "web_fetch": {
        "group": "web",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "fetch one web page",
    },
    "web_download": {
        "group": "web",
        "source": "adapter",
        "read_only": False,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": True,
            "shell": False,
            "network": True,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "download one remote file",
    },
    "browser_open": {
        "group": "browser",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "open a web page in the browser runtime",
    },
    "browser_click": {
        "group": "browser",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "click in the browser runtime",
    },
    "browser_type": {
        "group": "browser",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "type in the browser runtime",
    },
    "browser_wait": {
        "group": "browser",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "wait in the browser runtime",
    },
    "browser_scroll": {
        "group": "browser",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "scroll in the browser runtime",
    },
    "browser_snapshot": {
        "group": "browser",
        "source": "adapter",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": False,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "capture browser page state",
    },
    "browser_screenshot": {
        "group": "browser",
        "source": "adapter",
        "read_only": False,
        "requires_evidence": True,
        "requires": {
            "workspace_read": False,
            "workspace_write": True,
            "shell": False,
            "network": True,
            "browser": True,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "save a browser screenshot",
    },
    "image_read": {
        "group": "media",
        "source": "optional",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": ["Pillow"],
        },
        "risk": "medium",
        "summary": "read image content",
    },
    "image_inspect": {
        "group": "media",
        "source": "optional",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": ["Pillow"],
        },
        "risk": "low",
        "summary": "inspect image metadata",
    },
    "sessions_list": {
        "group": "session",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "list sessions",
    },
    "sessions_history": {
        "group": "session",
        "source": "native",
        "read_only": True,
        "requires_evidence": True,
        "requires": {
            "workspace_read": True,
            "workspace_write": False,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "low",
        "summary": "read one session history",
    },
    "archive_extract": {
        "group": "archive",
        "source": "native",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": True,
            "workspace_write": True,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": [],
        },
        "risk": "medium",
        "summary": "extract a local archive",
    },
    "mail_extract_attachments": {
        "group": "archive",
        "source": "optional",
        "read_only": False,
        "requires_evidence": False,
        "requires": {
            "workspace_read": True,
            "workspace_write": True,
            "shell": False,
            "network": False,
            "browser": False,
            "optional_dependency": ["extract-msg"],
        },
        "risk": "medium",
        "summary": "extract mail attachments",
    },
}


def get_tool_metadata(name: str) -> dict[str, Any]:
    tool_name = str(name or "").strip()
    if tool_name in TOOL_METADATA:
        return {
            **dict(TOOL_METADATA[tool_name]),
            "requires": dict((TOOL_METADATA[tool_name].get("requires") or {})),
        }
    return {
        **dict(FALLBACK_TOOL_METADATA),
        "requires": dict(FALLBACK_TOOL_METADATA.get("requires") or {}),
    }


def has_tool_metadata(name: str) -> bool:
    return str(name or "").strip() in TOOL_METADATA


def metadata_missing_names(tool_names: list[str] | tuple[str, ...] | set[str]) -> list[str]:
    missing = {str(name or "").strip() for name in tool_names if str(name or "").strip() and not has_tool_metadata(str(name or "").strip())}
    return sorted(missing)


__all__ = [
    "FALLBACK_TOOL_METADATA",
    "TOOL_GROUP_ORDER",
    "TOOL_METADATA",
    "get_tool_metadata",
    "has_tool_metadata",
    "metadata_missing_names",
]
